### ISSUE TITLE
Maven build failed

### ISSUE THREAD

**Issue by elasticlabs** [opengeospatial/ets-wms13-dgiwg#18]
Hi, the suite fails to build on a dockerized environment.

I packaged a working docker environment, but fails at building with maven the following suites : ets-wms13-dgiwg, ets-wfs20-dgiwg and gpkg12-nsg

## Environment : 
- Docker image from `tomcat:7.0-jdk8` base image (code at https://github.com/elasticlabs/teamengine-compose)
- User : root
- Maven information 
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_265, vendor: Oracle Corporation, runtime: /usr/local/openjdk-8/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.3.18-3-pve", arch: "amd64", family: "unix"
```
After running `git clone https://github.com/opengeospatial/ets-wms13-dgiwg.git` then keep master branch, I try to build the project like other TEAMEngine ETS and get the following error message : (seems that repository is not found)

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.opengis.cite:ets-wms13-dgiwg >------------------
[INFO] Building DGIWG WMS 1.3 profile Conformance Test Suite 0.4
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.opengis.cite:ets-dgiwg-core:jar:0.4 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.448 s
[INFO] Finished at: 2020-11-26T21:05:54Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ets-wms13-dgiwg: Could not resolve dependencies for project org.opengis.cite:ets-wms13-dgiwg:jar:0.4: Failure to find org.opengis.cite:ets-dgiwg-core:jar:0.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

Does the pom.xml file misses `<repository>` section?

Thank you very much by advance.

**Comment by dstenger** [comment]
Usually, the CITE artifacts a published on Central Maven Repository (https://search.maven.org/). However, some artifacts are missing (especially older ones).
Central Maven Repository is considered by default and there is no additional CITE Maven repository which could be referenced via `<repository>` section in the pom file.

In this case, the artifact `ets-dgiwg-core` is missing. As this artifact is not available via Central Maven Repository, you have to build it on your local machine (`mvn clean install`) so that it is available via local Maven repository. Unfortunately, this artifact is currently not available remotely.

This is the repository and the tag providing the source code to build the missing artifact: https://github.com/opengeospatial/ets-dgiwg-core/tree/0.4

**Comment by elasticlabs** [comment]
Thank you! I applied the recommandation, and the build works.

However, altough the ETS works with REST interface, it doesn't appear in TEAMEngine available suites, nor in $TE_BASE/config.xml
Is this a common issue? 

I'm working with TEAMEngine 5.4. Should I go back to previous version? Or 5.5?
Thank you much by advance.

**Comment by elasticlabs** [comment]
Sorry it seems more linked to my dokerfile, therefore I can close this issue. Thanks again :)
