### ISSUE TITLE
Test "invoke Base Test Suite"  fails with message "Unexpected status code."

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms13-dgiwg#4]
Tested with WMS 1.3 RI [1] on a local docker environment with the following versions:
 * TEAM Engine, 5.1-SNAPSHOT
 * ETS DGIWG WMS 1.3, 0.4-SNAPSHOT

The test `invoke Base Test Suite` (in CC `Queryable`) fails with the message `Unexpected status code.`.

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?request=GetCapabilities&service=WMS

**Comment by lgoltz** [comment]
It is tried to invoke the ETS WMS 1.3 via REST with the following URL:  http://cite.opengeospatial.org/te2/rest/suites/wms/1.16/%20wms/1.23/run 

Correct would be: http://cite.opengeospatial.org/te2/rest/suites/wms/1.23/run.

Using beta is fine for the moment since the REST API for WMS 1.3 is not enabled on alpha. But the path is duplicated and must be fixed. 
Ticket https://github.com/opengeospatial/teamengine/issues/261 should be solved first to avoid required adjustment of the version in the path.

**Comment by chuck1987** [comment]
I am also getting this issue with : http://mdms1-devel1.compusult.net/wes/GeopackageWMS/259?request=GetCapabilities

The rest of the test passes correctly, and I am not sure why the this test is failing? Do I need to return application/xml as the response format and not text/xml? Not sure why this test is failing. I am testing on the beta validation site.

**Comment by beattyj** [comment]
I've traced this issue to the WMSQueryable test constructing a URL within the code to test the prospective WMS service against an "official" OGC testsuite (whcih from the DGIWG perspective is redundant since it is an extension of the latest OGC testsuite) - this occurs when no "tes" parameter is provided (again, a redundant test from the DGIWG perspective)
However the default in the code in constructing this URL both hardcodes a query on the OGC beta test site for a (assumingly single) "wms" test suite and assumes an older specification version number (1.16).  The OGC beta does not contain only 1 wms test-suite, so the code (assuming a list of 1) tries to concatenate ALL found wms paths, creating a mishmash URL, which fails each time.
NOTE:  for a extended test-suites (aka the NSG WMS test suite) - this redundant test would not be allowed in a closed network environment (added as issue #, would recommend removing this test.

**Comment by beattyj** [comment]
The root cause of this issue occurs in the QueryableWMS class
There can be several solutions, based on whether it is still necessary to call an external OGC Test Run Controller (especially when the test is initiated with the {tes} parameter not provided or is blank).

I would recommend to remove this test (or replace with one not relying on an external URL), for those situations where TEAMEngine and this test suite must run in a stand-alone environment.

Regardless, the issue comes down to the construction of the default OGC URL for their test run controllers (at http://cite.opengeospatial.org/te2/).  
Inside `QueryableWMS.discoverTestRunController`, this default OGC site is queried for all paths the begin with 'wms' (see **LINE:A** below) and builds an XPath entity; however more than one URL exists that begins with 'wms', so when the test gets to **LINE:B** it extracts every entry it found: literally  `wms/1.24/ wms13-dgiwg/0.4/ wms13-nsg/0.2/ wms/1.18/` from the XPath (as opposed to simply the presumed desired `wms/1.24/`; and thus the URL that gets called becomes http://cite.opengeospatial.org/te2/rest/suites/wms/1.24/%20wms13-dgiwg/0.4/%20wms13-nsg/0.2/%20wms/1.18/run instead of what I can suspect should be simply http://cite.opengeospatial.org/te2/rest/suites/wms/1.24/run
Hence since the former URL does not exist, this test will always return a 400 error.
(recall the test asserts that the result is the 200 code)

`URI discoverTestRunController(URI tesEndpoint) {`
`        // fetch list of available test suites from TES`
`        URI targetURI = UriBuilder.fromUri(tesEndpoint).path("rest/suites/").build();`
`        WebResource resource = this.httpClient.resource(targetURI);`
`        ClientResponse rsp = resource.get(ClientResponse.class);`
`        if (!rsp.getStatusInfo().getFamily().equals(Response.Status.Family.SUCCESSFUL)) {`
`            throw new RuntimeException(String.format("Test execution service not available at %s", tesEndpoint));`
`        }`
`        // find WMS test run controller`
**LINE:A**
`        String xpath = "//html:li/html:a[starts-with(@id,'wms')]/@href";`
`        XdmValue xdmVal;`
`        Source entity = new StreamSource(rsp.getEntityInputStream(), targetURI.toString());`
`        try {`
`            xdmVal = XMLUtils.evaluateXPath2(entity, xpath, Collections.singletonMap(HTML_NS, "html"));`
`        } catch (SaxonApiException e) {`
`            throw new RuntimeException(`
`                    String.format("Failed to access list of test suites at %s. Reason: %s", targetURI, e.getMessage()));`
`        }`
`        if (xdmVal.size() == 0) {`
`            throw new RuntimeException(String.format("WMS test suite is not listed at %s", targetURI));`
`        }`
`        URI controllerUri = null;`
`        try {`
**LINE:B**
`            String etsPath = xdmVal.getUnderlyingValue().getStringValue();`
`            controllerUri = UriBuilder.fromUri(targetURI).path(etsPath).path("run").build();`
`        } catch (XPathException e) {`
`            // not possible with atomic value`
`        }`
`        return controllerUri;`
`    }`


Possible solutions

1. As suggested, remove the test or rewrite to **NOT** include a call to an external URL (for the sake of hardened or closed system implementations of TEAMEngine)

2. Or:  At **LINE:A**, change the search for 'wms' to more specific search (i.e. 'wms13-nsg') - **HOWEVER**, the accepted parameters for that Test Run Controller are not the same (the 'queryable' parameter, for example) as the wms/1.24 accepted parameters

3. Or:  At **LINE:B** swap-out the `.getUnderlyingValue` call for `.itemAt(0)`. This way only the first item is used to build the Test Run Controller URL - **HOWEVER** this makes the assumption that the desirable WMS Test Run Controller is the first in the list.  (in retrospect, I suppose, a loop could be introduced here to search for the specific wms and version)

**Comment by lgoltz** [comment]
@beattyj Thanks for your investigation!

I propose to enhance the REST API and access via TEAM Engine that the user can choose between 
  1. using the default URL to include an existing WMS Core test suite
  1.  pass an URL to a running WMS Core test suite
  1.  skip the entirely test (e.g. it the WMS Core test suite was already tested separately)

2. is already implemented partly (parameter TES). 

For 1. and 2. it is required to fix the test as the correct test suite is selected. I propose to enhance the existing REST API of the TEAM Engine for an XML (or JSON) output to avoid parsing the HTML. At least parsing the HTML must be fixed to select the correct WMS Core test suite. 
As the version of the specification is only described in the link text parsing the HTML is somewhat less then perfect (see example below from http://cite.opengeospatial.org/te2/rest/suites/).

```
<li>
 <a href="wms/1.24/" id="wms-1.24" type="text/html">Conformance Test Suite - OGC Web Map Service 1.3.0</a>
</li>
<li>
 <a href="wms/1.18/" id="wms-1.18" type="text/html">Conformance Test Suite - OGC Web Map Service 1.1</a>
</li>  
```

@beattyj Do you agree with this proposal?

**Comment by lgoltz** [comment]
Duplicate of #8
